"""HTTP API layer - Views and Serializers."""

from .auth_views import (
    signup,
    login,
    me,
    user_payload,
    tokens_for_user,
)

from .student_views import (
    class_list,
    enroll,
    class_detail,
    quit_class,
    all_assignments,
    submit_assignment,
    unsubmit_assignment,
    account_stats,
)

from .teacher_views import (
    teacher_students,
    teacher_class_list,
    teacher_stats,
    teacher_class_detail,
    teacher_add_student,
    teacher_remove_student,
    teacher_add_announcement,
    teacher_delete_announcement,
    teacher_add_assignment,
    teacher_edit_assignment,
    teacher_delete_assignment,
    teacher_add_lecture,
    teacher_delete_lecture,
    teacher_grade_submission,
)

from .ai_views import (
    AI_COURSES_ROOT,
    teacher_upload_ai_course,
    teacher_delete_ai_course,
    ai_course_status,
    ai_courses_for_class,
    ai_course_page,
    ai_course_ask,
    ai_course_reformulate,
    request_concept_animation,
    get_animation_status,
    list_course_animations,
    generate_quiz_view,
    get_quiz_status,
    get_quiz_questions,
    submit_quiz_attempt,
    get_quiz_results_for_teacher,
)

__all__ = [
    'signup',
    'login',
    'me',
    'user_payload',
    'tokens_for_user',
    'class_list',
    'enroll',
    'class_detail',
    'quit_class',
    'all_assignments',
    'submit_assignment',
    'unsubmit_assignment',
    'account_stats',
    'teacher_students',
    'teacher_class_list',
    'teacher_stats',
    'teacher_class_detail',
    'teacher_add_student',
    'teacher_remove_student',
    'teacher_add_announcement',
    'teacher_delete_announcement',
    'teacher_add_assignment',
    'teacher_edit_assignment',
    'teacher_delete_assignment',
    'teacher_add_lecture',
    'teacher_delete_lecture',
    'teacher_grade_submission',
    'AI_COURSES_ROOT',
    'teacher_upload_ai_course',
    'teacher_delete_ai_course',
    'ai_course_status',
    'ai_courses_for_class',
    'ai_course_page',
    'ai_course_ask',
    'ai_course_reformulate',
    'request_concept_animation',
    'get_animation_status',
    'list_course_animations',
    'generate_quiz_view',
    'get_quiz_status',
    'get_quiz_questions',
    'submit_quiz_attempt',
    'get_quiz_results_for_teacher',
]
