# Generated by Django 5.2.14 on 2026-05-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_submission_grade_submission_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/assignments/'),
        ),
        migrations.AddField(
            model_name='lecturefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/lectures/'),
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
