# Generated by Django 5.2.14 on 2026-05-27 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_assignmentattachment_file_lecturefile_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('filename', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready'), ('ERROR', 'Error')], default='PROCESSING', max_length=20)),
                ('total_pages', models.IntegerField(default=0)),
                ('error_msg', models.TextField(blank=True)),
                ('output_dir', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_courses', to='api.class')),
            ],
        ),
    ]
