# Generated by Django 5.2.14 on 2026-05-28 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_aicourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptAnimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.TextField()),
                ('concept_key', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating code'), ('RENDERING', 'Rendering video'), ('READY', 'Ready'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='animations/')),
                ('retry_count', models.IntegerField(default=0)),
                ('error_msg', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animations', to='api.aicourse')),
            ],
            options={
                'unique_together': {('ai_course', 'concept_key')},
            },
        ),
    ]
