# Generated by Django 5.2.14 on 2026-05-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_conceptanimation'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicourse',
            name='current_step',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('EXTRACTING', 'Extracting PDF'), ('NARRATING', 'Generating narration'), ('TTS', 'Generating audio'), ('CHROMA', 'Building ChromaDB'), ('DONE', 'Done')], default='PENDING', max_length=20),
        ),
    ]
